name: Build Website

on: [push, workflow_dispatch]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: website    
          submodules: true

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Installing Packages
        run: yarn install

      - name: Build
        env:
          NODE_ENV: production
        run: yarn export && touch ./out/.nojekyll

      - name: Copy Generated Static Site
        run: cp -r out/ ../tempdir

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          submodules: true
      
      - name: Copy Generated Static Site to Main
        run: yes | cp -rf ../tempdir ./
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Website Auto Deploy

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: gh-pages

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: "--no-verify --signoff"

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .

          # Optional commit user and author settings
          commit_user_name: WebsiteBot
          commit_user_email: jaysmito101@gmail.com
          # commit_author: DocumentationBot <jaysmito101@gmail.com>

          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          add_options: "--all"

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          push_options: "--force"

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true

          # Optional. Skip internal call to `git checkout`
          skip_checkout: true

          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
