name: Deploy Documentation

on: [push]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Docs
        run: scripts\DeployDocs.bat

      - uses: actions/upload-artifact@v2
        with:
          name: TerraForge3D Docs
          path: Docs\html
