# This is a basic workflow to help you get started with Actions

name: Linux Debug Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
         submodules: true
         
      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"
        
      - name: Generate Solution
        run: premake5 gmake2

      - name: Install Requied Libraries
        run: |
          sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
          sudo apt-get install libxmu-dev libxi-dev
          sudo apt-get install mesa-utils
          sudo apt-get install freeglut3-dev

      # Runs a single command using the runners shell
      - name: Build
        run: make -j8
        
      - uses: actions/upload-artifact@v2
        with:
           name: TerraForge3D Debug Build (Linux)
           path: bin\Debug-linux-x86_64
      
        
          
          
